### ISSUE TITLE
Options for the loader

### ISSUE THREAD

**Issue by ThomasWeinert** [FluentDOM/HTML5#1]
Allow to configure the HTML5 parser, by providing options to the loader.

**Comment by iotch** [comment]
Hello. To not to open a new issue - it seems like "xmlNamespaces" option is missing in the loader? https://github.com/Masterminds/html5-php#xml-namespaces

**Comment by ThomasWeinert** [comment]
Hello,

don't be afraid to create new issues. It makes it easier to handle,
actually.

I created one for your request.
https://github.com/ThomasWeinert/FluentDOM-HTML5/issues/4

It would be nice if you could add a small usage example to it. It would
give me a better idea for the implementation and unit tests.

Best Regards
Thomas
